### ISSUE TITLE
Docs overhaul

### ISSUE THREAD

**Issue by zkat** [zkat/mona#10]
I really don't like the docs situation right now -- they're off on this separate site. They're generated by this awful tool. They take up immense amount of space in code that should be easy to just scroll through.

My current preference is to yank out all the code comments and move them into the README.md, but I may need to think of that a bit more before pulling it off.

Whatever it is, though, I don't want to keep using the current generator, and I really really want it to be an easy reference hosted in the sources.

**Comment by davidchambers** [comment]
One option to consider is [Transcribe](https://github.com/plaid/transcribe). I use it to generate [Sanctuary](https://github.com/plaid/sanctuary)'s README because I appreciate beautiful source code as well as nice documentation. JSDoc is ugly to my eye.

Disclaimer: I am one of Transcribe's authors.

**Comment by zkat** [comment]
This looks great!

I'm still weighing whether I want to remove all the comments from the source, because it's a lot of noise.

I'll give it a shot and see how it works.

The funny thing is, I was feeling hesitant about using Haskell-style type specs, which is hilarious considering how it's a library based on Parsec. ;)

Gotta figure out how to do optional values, though :s

**Comment by zkat** [comment]
I've rewritten the readme! It should be much nicer now, and I'll work on automating this in the future if it actually makes sense to. For now, hand-writing it is less effort. :)
