### ISSUE TITLE
real parser incorrect

### ISSUE THREAD

**Issue by katyo** [zkat/mona#2]
Hello, @zkat.

I happy to use your awesome parser combinator for parsing some complex things, like math expressions, and it works really fine in resumable (async) mode. I also tried to use parsimmon and bennu, but it not so good as mona-parser. Great thanks for this library.

Of course, I also found the incorrect behavior of some basic parser:

``` coffeescript
coffee> parse real(), "0.100"
1
coffee> parse real(), "0.800"
0.8
coffee> parse real(), "0.080"
0.8
coffee> parse real(), "-0.080"
0.8
coffee> parse real(), "-1.080"
-1.8
```

**Comment by zkat** [comment]
thanks for the report! there's a pretty significant test suite that covers just about every parser and I'm not at all surprised there are some corner cases. I'll take a look at this one, unless you feel like poking at the code yourself.

I'm glad you're having a good time using the parser! it's served me well, too :)

**Comment by katyo** [comment]
I tried to fix float parser using floating point arithmetic, but this way has a unresolved problems related to a rounding:

```
AssertionError: 1.2000000000000002 == 1.2
```

My fixed version looks like so:

``` javascript
function real() {
  return sequence(function(s) {
    var sign = s(or(string("+"),
                    string("-"),
                    value("")));
    var leftSide = s(text(digit(), {min: 1}));
    var rightSide = s(or(and(string("."),
                             text(digit())),
                             value("")));
    leftSide = parseInt(sign+leftSide+rightSide, 10);
    var expo = s(or(and(string("e", false),
                    integer()),
                 value(0))) - rightSide.length;
    return value(leftSide*(Math.pow(10, expo)));
  });
}
```

So, I don't know nothing more universal than applying parseFloat to a concatenation of all taken numeric tokens.

**Comment by zkat** [comment]
This is in develop with 6b5631e.

Turns out, btw, that if you do an actual loop that divides by ten, it gets rid of the floating point issue? I should probably think a bit more about that -- but this is fixed now, specially after some tweaks.

I found another issue while testing this where `-.8` wasn't parsing -- so we can parse that now, too.
