### ISSUE TITLE
Set userState as context of bind/map functions.

### ISSUE THREAD

**Issue by katyo** [zkat/mona#4]
I see a `userState` field in `ParserState` object, but I don't see any ways for use it. I offer set this as context for functions, which used with `bind` and `map`. I need this feature to create some stateful parsers. So I implemented the next variants of bind and map yet:

``` javascript
function bindState(parser, fun) {
  return bind(parser, function(result) {
    return function(parserState) {
      return fun.call(parserState.userState, result)(parserState);
    };
  });
}

function mapState(transformer, parser) {
  return bindState(parser, function(result) {
    return value(transformer.call(this, result));
  });
}
```

**Comment by katyo** [comment]
I just used an option `userState` as contexts of functions, which passed to a bind()/map() 36c167d1d680019b5c35d8bccfb776c5fbe29c9f

**Comment by zkat** [comment]
This is in develop with 6b5631e.
