### ISSUE TITLE
`join` combinator like `and` but collect results

### ISSUE THREAD

**Issue by katyo** [zkat/mona#5]
Often we want join several parsers (i.e. sequential as `and`) and provide results as array. For example, we may use monadic combinator `sequence` to implement it, like so:

``` javascript
function ourParser() {
  return sequence(function(s){
    return value([
      s(parser1()),
      s(parser2()),
      ...
      s(parserN())
    ]);
  });
}
```

But that general way poorly adapted to use each time. So I offer implement special `join` combinator (An idea is close to applicative functors):

``` coffeescript
# CoffeeScript
join = (parsers...)-> sequence (s)-> value (s parser for parser in parsers)
```

``` javascript
// JavaScript
function join() {
  var parsers = arguments;
  return sequence(function(s){
    var results = new Array(parsers.length);
    for(var i = 0; i < parsers.length; i++)
      results[i] = s(parsers[i]);
    return value(results);
  });
}
```

This can be used like `and`, but returns array with results of all parsers.

**Comment by katyo** [comment]
I implemented this feature at 53ada87df15db745cab860c812b6756563b55ae1

**Comment by zkat** [comment]
Hey @katyo -- I thought I'd give you a heads-up in one of these issues. I've been having a hell of a week, and I'm going to try to catch up with all these this weekend or so. Is that alright?

These are awesome and I really appreciate it! Thank you!! I don't want to make you feel ignored :)

**Comment by zkat** [comment]
This is in develop with 6b5631e.
