### ISSUE TITLE
Using iteration instead of recursion in basic combinators

### ISSUE THREAD

**Issue by katyo** [zkat/mona#6]
As I can see, a bundled basic combinators, like an and()/or() using recursion. But recursion is one of bad things which we should to try to avoid in JavaScript everywhere, where it is just possible.

I offer iterative versions of and()/or() combinators, which fully compatible with recursive implementations (all tests passed successfully) c53a9e9aabc4fcfc396018cf13f3c207c83c2701

**Comment by katyo** [comment]
Hmm....
This improvements increases performance up to six times in some my own tests (for example, parsing time decreased from 1359ms to 231ms).

**Comment by zkat** [comment]
This is in develop with 6b5631e.
