### ISSUE TITLE
Travis CI related issues

### ISSUE THREAD

**Issue by katyo** [zkat/mona#7]
I see, that Travis CI can't install some build dependencies for older versions of NodeJS (0.8, 0.6) and NPM. As result we have an integration issues, which not related to a library itself.

It's looks like a incompatibility issues. Maybe just turn off a support for older versions and add a new versions instead.

**Comment by zkat** [comment]
I've poked at the .travis.yml some more, and I think the platforms there now are the ones I'd actually like to target.
